GUILD_ID = 1110915298535677952
CARGO_ID_PRETENDENTE = 1111854719019782154
CARGO_ID_EVERYONE = 1110915298535677952
CARGO_ID_ALUNOS = 1111846873192472609
CARGO_ID_PROFESSORES = 1116047094847909979
PASTA_DATA = '/data'
SITUACAO_CADASTROS_CSV = 'situacao_cadastros.csv'
MONITORES_CSV = 'monitores.csv'
COLUNA_DISCIPLINAS_MONITORES_CSV = 'disciplinas'
COLUNA_MONITORES_CSV = 'monitores'
ALUNOS_CSV = 'alunos.csv'
PROFESSORES_CSV = 'professores.csv'
PROFESSORES_CSV_COLUNA_NOME = 'Nome'
PROFESSORES_CSV_COLUNA_EMAIL = 'E-mail'
ALUNOS_CSV_COLUNA_NOME = 'Nome'
ALUNOS_CSV_COLUNA_MATRICULA = 'Matricula'
ALUNOS_CSV_COLUNA_CURSO = 'Curso'
ALUNOS_CSV_COLUNA_SITUACAO = 'Situacao'
ALUNOS_CSV_COLUNA_PERIODO_INGRESSO = 'Periodo letivo de ingresso'
ALUNOS_CSV_COLUNA_EMAIL_PESSOAL = 'E-mail pessoal'
ALUNOS_CSV_COLUNA_EMAIL_ACADEMICO = 'E-mail academico'
COLUNA_EMAIL_SITUACAO_CADASTROS_CSV = 'E-mail'
COLUNA_SITUACAO_CADASTROS_CSV = 'Situacao'
COLUNA_USUARIO_SITUACAO_CADASTROS_CSV = 'Usuario'
COLUNA_CODIGO_SITUACAO_CADASTROS_CSV = 'Codigo'
COLUNA_NOME_ALUNOS_PROFESSORES_CSV = 'Nome'
PASTA_PLANILHAS = '/planilhas'
ARQUIVO_LOG = 'log.txt'
BANIDOS_CSV = 'banidos.csv'
COLUNA_ID_USUARIOS_BANIDOS_CSV = 'Id_usuario'
COLUNA_HORA_BAN_BANIDOS_CSV = 'Hora_ban'
COLUNA_HORA_DESBAN_BANIDOS_CSV = 'Hora_desban'
COLUNA_MATRICULADOS_DISCIPLINAS_CSV = 'matriculados'
# DISCIPLINAS = ['algoritmos.csv', 'teste.csv']
# CARGOS_DISCIPLINAS = [
#     {
#         'nome': 'algoritmos',
#         'cargo_id_discord': 1120870080562081822,
#     },
#     {
#         'nome': 'teste',
#         'cargo_id_discord': 1120870943460442245,
#     }
# ]
    
